src/components/Nav.tsx

-
<br>
- 반응형 Nav SideBar 구현
<br>
- ***
close #이슈번호

feat: 반응형 Nav - SideBar

---

src/components/Live/CalendarPopUp.tsx
src/components/Live/MentorProfile.tsx
src/components/Live/PopUp.tsx
src/components/Live/ShowMentoring.tsx
src/components/Live/ShowSchedule.tsx
src/pages/Mentoring.tsx

- 일정 관리 페이지 생성
<br>
- 일정 관리 페이지를 만들었습니다
- 토글로 일정 및 전체 페이지 전환 기능 생성하였습니다
- 캘린더 시간 단위 1시간으로 변경하였습니다
<br>
close #15

feat: 일정 관리 페이지 생성

---

src/components/Live/LiveList.tsx

- 멘토링룸 목록 조회 화면에서 비율이 바뀌어도 레이아웃이 깨지지 않도록 수정
<br>
- 멘토링룸 목록 조회 화면에서 비율이 바뀌어도 레이아웃이 깨지지 않도록 수정
<br>
close #이슈번호

fix: 화면 비율 맞추기

---

src/components/Live/LiveList.tsx
src/components/Live/RoomList.tsx
src/pages/Mentoring.tsx
yarn.lock

- 멘토링 룸 전체 목록 조회
<br>
- 멘토링 룸 전체 목록 조회를 Test DB를 통해 무한 스크롤로 구현하였습니다
- 협업 중인 컴포넌트 통합을 완료하였습니다
<br>
close #29

feat: 멘토링 룸 무한 스크롤 구현 및 통합

---

src/components/Live/CreateRoomModal.tsx
src/components/Live/CreateScheduleModal.tsx
src/pages/Mentoring.tsx

- 멘토링 룸에 대한 스케줄 추가 모달창 구현
<br>
- 멘토링룸 생성 후, 스케줄 추가 모달 창 수정
<br>
close #24

feat: 멘토링 룸에 대한 스케줄 추가 모달창

---

.gitignore
src/App.tsx
src/components/Layout.tsx
src/components/Nav.tsx
src/pages/Main.tsx
src/pages/MyPage.tsx
src/pages/SignUp.tsx

- 향후 api 테스트위해 최상위에`.env`파일 생성 후 .gitignore에 추가하여 서버 주소 숨김
- 최상위에`.env`파일 생성 후 밑에 코드에 `서버 url` 추가하면 됨
```
REACT_APP_DEV_URL='테스트할 서버url'
```
<br>
- MyPage 기본 UI 진행중
- 공통 Layout 수정 
데스크탑 화면에서 양쪽 여백이 너무 적으므로 데스크탑에서 여백 더 주는 css로 Layout 변경함
- Nav 상단 고정
스크롤해도 상단에 Nav 고정됨
<br>
- ***
close #이슈번호

feat: Mypage, Layout수정, Nav 상단 고정

---

src/components/Live/CalendarPopUp.tsx
src/components/Live/LiveList.tsx
src/components/Live/RoomList.tsx
src/components/Live/ShowMentoring.tsx
src/components/Live/ShowSchedule.tsx
src/index.tsx
src/pages/Mentoring.tsx

- 무한 스크롤 수정 및 검색 구현
<br>
- 무한 스크롤 오류(데이터 가져오는 범위)를 해결하였습니다
- 
- 검색 기능을 구현하였습니다
- 
<br>
close #35 #34

feat: 무한 스크롤 수정 및 검색 구현

---

src/components/live/MentorProfile.tsx
src/components/live/RoomList.tsx
src/components/live/ShowMentoring.tsx

- 방 정보 소개 페이지 수정
<br>
- 더미 데이터로 구현되었던 방 정보 소개 페이지를 클릭한 방 정보를 가져오게 수정하였습니다
<br>
close #24 #41

feat: 방 정보 소개 페이지 업데이트

---

src/pages/MyPage.tsx

-
<br>
- import해온 Live -> live 로 변경
<br>
- ***
close #이슈번호

chore: 소문자변경

---

package.json

- react-dropzone 의존성 추가
<br>
- react-dropzone 의존성이 누락되어 pakage.json에 추가했습니다.
<br>

fix: react-dropzone 라이브러리 의존성 추가

---

src/components/live/CalendarPopUp.tsx
src/components/live/CreateScheduleModal.tsx
src/components/live/LiveList.tsx
src/components/live/MentorOption.tsx
src/components/live/RoomList.tsx
src/components/live/ShowMentorOption.tsx
src/components/live/ShowMentoring.tsx
src/pages/Mentoring.tsx

- 멘티 신청 및 일정 조회, 방 정보 등 구현
<br>
- 일정 조회 기능을 수정하였습니다
- 멘티 일정 신청을 추가하였습니다
- 일정에 따른 스케쥴 변동을 완성하였습니다
<br>
- 주석 친 내용은 멘토의 방 삭제로 곧 구현할 예정입니다
close #53
close #52

feat: 멘티 신청 및 추가 기능

---

src/components/live/CreateRoomModal.tsx
src/components/live/CreateScheduleModal.tsx
src/components/live/LiveList.tsx
src/components/live/MentorScheduling.tsx
src/components/live/ModifyRoomInfo.tsx
src/components/live/ModifySchedule.tsx
src/pages/Mentoring.tsx

- 멘토의 멘토링룸 관리 페이지 개설
<br>
- 멘토의 멘토링룸 관리 페이지 개설 후, 멘토링룸 조회까지 구현했습니다.
<br>
close #55

feat: mentor setting page

---

src/components/live/CalendarPopUp.tsx
src/components/live/ShowSchedule.tsx
src/pages/Mentoring.tsx
yarn.lock

- 멘토링 방 입장 개발 중
<br>
- 멘토링 방 입장 로직 구현 중입니다
- CORS 설정 문제로 인해 live-session 로직 수정 예정입니다
<br>
- @kcs-developers/start-dream-team @soojik @Jooney-95 
- CORS 설정을 서버 쪽에서 수정해야 하므로 현재 작업 중인 내역만 올립니다
close #이슈번호

feat: 멘토링 방 입장

---

src/components/live/ShowSchedule.tsx

- 멘티 입장 로직
<br>
- 멘티 입장 로직 작성하였습니다
<br>
- @kcs-developers/start-dream-team @soojik @ITfervor 
- 오류 발생 가능성 농후하여 수정 예정입낟
close #66

feat: 멘티 입장

---

src/components/live/ShowSchedule.tsx

- 방 입장 로직 수정
<br>
- 방 입장 로직 수정하였습니다
- 사용자의 상태 값에 따른 처리 추가하였습니다
<br>
close #이슈번호

fix: 방 입장 수정

---

src/apis/axiosConfig.ts
src/components/Nav.tsx
src/components/mypage/AddressInput.tsx
src/components/mypage/NicknameInput.tsx
src/components/mypage/ResumeEdit.tsx
src/libs/checkJwtExp.ts
src/libs/localStorage.ts
src/libs/parseJwt.ts
src/pages/Login.tsx
src/pages/MyPage.tsx

1. axios.get 말고 `axiosInstance.get`해서 사용하기 
- `import { axiosInstance } from "apis/axiosConfig";` 이렇게 import도 하기
2. 최상위 폴더에 `.env`파일 생성 후 밑에 코드에 본인url 넣어서 추가하기
- `REACT_APP_DEV_URL='테스트할 서버URL 입력하기'`
1. 공통 URL을 axiosInstance 한 곳에서 지정하므로 `axiosInstance.get('/api/member')`이렇게 path만 적어주면 됨
2. 공통 URL이 아닌 API 마다 URL이 다르게 하고싶다면 `axiosInstance.get('본인URL/api/member')` URL도 다 적어서 덮어쓰기하면 됨
3. 위 사항 확인했다면 슬랙에 ✅ 남겨주세요
<br>
- 모든 요청에 Access token 담는 작업 구현함
- `axiosInstance`로 토큰담는 로직 구현했으므로 `axiosInstance.get` 이런식으로 사용해야 함. 그러면 모든 요청에 토큰 담김
- 참고 - `axios.get`하면 요청에 토큰 안담김
- 사용 예시
```tsx
import { axiosInstance } from "apis/axiosConfig";
//...
const { data } = await axiosInstance.get(`/api/member/${res.data.memberId}` );
console.log('받아진 데이터', data)
```
-  axiosInstance애서 공통 baseURL 지정하고 있음
```ts
export …
```

feat: 모든 요청에 JWT담기(axios interceptors), 로그인 후 유저정보 셋팅

---

src/components/live/CreateScheduleModal.tsx
src/components/live/MentorScheduling.tsx
src/components/live/ModifyRoomInfo.tsx
src/components/live/ModifySchedule.tsx
src/components/live/RoomList.tsx
src/components/live/ShowSchedule.tsx
src/pages/Mentoring.tsx

- schedule timeslot display 수정
<br>
- 기존에 일정 등록할 때 등록가능한 시간대 블럭 나타내는데에 일어났던 오류 수정
datepicker 로 날짜를 선택하면 신청가능한 시간만 나오도록 해야하는데, 날짜를 바꿀때마다 update 가 안되어서 수정했습니다.
<br>
close #이슈번호

fix: schedule timeslot

---

src/apis/apis.ts
src/apis/axiosConfig.ts
src/components/mypage/CareerInput.tsx
src/components/mypage/PwdInput.tsx
src/components/mypage/ResumeEdit.tsx
src/pages/Login.tsx
src/pages/MyPage.tsx

-
<br>
- access 토큰 만료시 갱신하는 로직 추가
- mypage   
- 내 정보 관리 - 닉네임,거주지 수정 완료 / 비밀번호변경 - 비밀번호 일치여부 테스트 필요
- 커리어정보 - 소개,기술,직무 수정완료   / 경력 api 테스트 필요
- 유저정보 조회 로직 수정
-  npm start하고 처음 로그인 시도하면 유저정보 조회 에러 발생해서 해당 조회 로직 수정함
<br>
- ***
close #이슈번호

feat: 토큰 만료시 갱신하기, mypage 수정, 

---

src/components/live/CalendarPopUp.tsx
src/components/live/LiveList.tsx
src/components/live/ModifySchedule.tsx
src/pages/Mentoring.tsx

- 서버와 주고받는 데이터 형식 수정
<br>
- 서버에서 던져주는 데이터의 변화로 일부 주고받는 데이터 형식 수정
<br>
close #이슈번호

fix: data format

---

src/components/live/LiveList.tsx
src/components/live/MentorScheduling.tsx
src/components/live/RoomList.tsx
src/components/live/ShowSchedule.tsx

- feat: 방 입장 및 브라우저 새로고침
<br>
- 방 입장 / 삭제 로직을 추가하였습니다
- 브라우저 새로고침을 추가하였습니다
<br>
close #79

feat: 방 입장 및 브라우저 새로고침

---

public/index.html
src/apis/apis.ts
src/components/MainList.tsx
src/components/MainListTitle.tsx
src/components/Nav.tsx
src/components/icons/MenuCloseIcon.tsx
src/components/mypage/CareerInput.tsx
src/components/mypage/ResumeEdit.tsx
src/pages/Login.tsx
src/pages/Main.tsx
src/pages/MyPage.tsx

-
<br>
1. 마이페이지
- 경력 CRUD - 이전 경력있을 시/ 없을 시로 분기
2. 메인 
- UI 수정
- 최근 등록된 문제 - 더미 데이터로 세팅
- 최근 개설된 채팅방 - api 조회 완료 
3. title Developers로 변경
- `MenuCloseIcon`아이콘 수정 => 밑처럼 width, height 설정해줘야 함
```tsx
<MenuCloseIcon
fill="black"
width={36}
height={36}
/>
```
- `apis/apis.ts` 에서 api 관리 중
<br>
- ***
close #이슈번호

feat: MyPage 경력 완료, 메인 UI 수정, title 추가

---

Jenkinsfile

- Jenkinsfile 수정
<br>
- Jenkinsfile 수정
<br>
close #이슈번호

docs: add Jenkinsfile

---

src/components/live/LiveList.tsx
src/components/live/MentorProfile.tsx
src/components/live/RoomList.tsx
src/components/live/ShowMentoring.tsx
src/components/live/ShowSchedule.tsx
src/pages/Mentoring.tsx

- fix&&feat: subscriptions and logic
<br>
- fix&&feat: subscriptions and logic
<br>

fix&&feat: subscriptions and logic

---

src/pages/Mentoring.tsx

- fix: view problem solve
<br>
- 구독 목록 조건문 변경
<br>
close #이슈번호

fix: view problem solve

---

src/pages/Mentoring.tsx

- fix: mentoring page 수정
<br>
- fix: mentoring page 수정
<br>
- ***
close #이슈번호

fix: mentoring page 수정

---

Jenkinsfile

- HTTPS 통신을 위한 Jenkinsfile 수정
<br>
- HTTPS 통신을 위해 Jenkinsfile에서 `REACT_APP_DEV_URL` 환경변수 값을 수정했습니다.
<br>

[Fix] HTTPS 통신을 위한 Jenkinsfile 수정

---

src/pages/Mentoring.tsx

- fix: mentoring list modify
<br>
- fix: mentoring list modify
<br>
close #이슈번호

fix: mentoring list modify

---

src/pages/Mentoring.tsx

- mentoring page 수정
<br>
- mentoring page 수정
<br>
close #이슈번호

fix: mentoring page

---

nginx.conf

- HTTPS 접속을 위한 nginx.conf 수정
<br>
- HTTPS 접속을 위해서 nginx에서 80과 443을 listen하도록 수정했습니다.
<br>

[Fix] HTTPS 접속을 위한 nginx.conf 수정 

---

src/components/live/MentorProfile.tsx
src/pages/Mentoring.tsx

- fix: mentorig btn css modify && notify
<br>
- 멘토링 버튼 스타일 수정하였습니다
- api 요청 url 수정하였습니다
<br>
close #이슈번호

fix: mentorig btn css modify && notify

---

src/components/Carousel.tsx
src/components/MainList.tsx
src/components/MultiOptions.tsx
src/components/icons/PencilIcon.tsx
src/components/mypage/ResumeEdit.tsx
src/pages/MyPage.tsx

-
<br>
1. 마이페이지
- 프로필 사진 등록
- 직무있을 시 직무명 로드
- 전체저장 완료 시 alert 완료 메시지
<br>
- ***
close #이슈번호

feat: MyPage avatar image, 직무 수정

---

src/components/live/CalendarPopUp.tsx
src/components/live/CreateRoomModal.tsx
src/components/live/CreateScheduleModal.tsx
src/components/live/LiveList.tsx
src/components/live/MentorProfile.tsx
src/components/live/MentorScheduling.tsx
src/components/live/ModifySchedule.tsx
src/components/live/PopUp.tsx
src/components/live/RoomList.tsx
src/components/live/SearchBar.tsx
src/components/live/ShowMentoring.tsx
src/pages/Mentoring.tsx

- 멘토링룸 디자인 수정
- 비회원 로직 추가
<br>
- 버튼 색, 반응형 웹 처리, 모달창 비율 등 수정
- 비회원일때의 처리 추가 구현
<br>
close #이슈번호

style: fix mentoring design

---

src/components/live/MentorProfile.tsx
src/pages/Mentoring.tsx

- fix: subscribe body modify
<br>
- fix: subscribe body modify 넘겨주는 body 타입 수정하였습니다
<br>
close #이슈번호

fix: subscribe body modify

---

src/components/live/MentorProfile.tsx

- fix: axios body data type modify
<br>
- fix: axios body data type modify
<br>
- ***
close #이슈번호

fix: axios body data type modify

---

src/components/live/MentorProfile.tsx
src/pages/Mentoring.tsx

- fix: 요청 주소 변경
<br>
- fix: 요청 주소 변경 수정
<br>
close #이슈번호

fix: 요청 주소 변경

---

src/pages/Mentoring.tsx

- fix: 조건 수정
<br>
- fix: 조건 수정
<br>
close #이슈번호

fix: 조건 수정

---

src/apis/apis.ts
src/components/MainList.tsx
src/pages/Main.tsx

-
<br>
1. 메인페이지
- 최근, 추천순 문제 조회
- but) 문제, 멘토링 모두 상세페이지로 연결이 안됨
<br>
- ***
close #이슈번호

feat: 메인페이지 problem 조회

---

src/components/live/CalendarPopUp.tsx
src/components/live/CreateRoomModal.tsx
src/components/live/CreateScheduleModal.tsx
src/components/live/LiveList.tsx
src/components/live/MentorProfile.tsx
src/components/live/ModifyRoomInfo.tsx
src/components/live/ModifySchedule.tsx
src/components/live/PopUp.tsx
src/components/live/RoomList.tsx
src/components/live/SearchBar.tsx
src/components/live/ShowMentoring.tsx
src/pages/Mentoring.tsx

- live mentoring 파트 디자인 수정
<br>
- 메인 디자인 통일 및 부가적인 기능(비회원일 때의, 멘토가 아닐 때 등의 상황 처리) 수정이 있었습니다.
- 사용자의 멘토링 신청 시 member 측으로 포인트 차감 요청이 추가되었습니다.
<br>
close #

fix: live mentoring design

---

src/components/live/ShowSchedule.tsx

- mentoring entering 로직 수정
<br>
- mentoring entering 로직 수정
<br>
close #이슈번호

fix: mentoring entering

---

src/pages/Mentoring.tsx

- 저장되는 title 수정
<br>
- `title with mentor/mentee name` 형식으로 저장되던 데이터 수정
<br>
close #이슈번호

fix: 저장되는 title 수정

---

src/components/S3Box.tsx
src/components/SearchBox.tsx
src/components/dropbox/DropBoxCondition.tsx
src/components/dropbox/DropBoxLevel.tsx
src/components/dropbox/DropBoxSolved.tsx
src/components/problem/ClientDetailob.tsx
src/components/problem/ClientDetailsb.tsx
src/components/problem/ProblemPointModal.tsx
src/components/problemRegister/ProblemRegisterBox.tsx
src/pages/Problem.tsx

- 메인페이지 수정 및 포인트 axios
<br>
- 메인페이지 수정 최신순 정렬
<br>
- @kcs-developers/start-dream-team @Jooney-95 @EagerProgrammer 
close #이슈번호

[Fix] 메인 페이지 수정

---

src/components/problemRegister/ProblemRegisterBox.tsx

- axiosInstance제거
<br>
- axiosInstance제거
<br>
- @kcs-developers/start-dream-team @Jooney-95 
close #이슈번호

fix: axiosInstance제거

---

src/App.tsx
src/components/live/CreateRoomModal.tsx
src/components/live/LiveList.tsx
src/components/live/MentorProfile.tsx
src/components/live/MentorScheduling.tsx
src/components/live/Modal.tsx
src/components/live/ModifyRoomInfo.tsx
src/components/live/ModifySchedule.tsx
src/components/live/RoomList.tsx
src/components/live/ShowMentoring.tsx
src/components/live/ShowSchedule.tsx
src/pages/Mentoring.tsx

- feat: notify && fix: session service
<br>
- 알림 기능 1차 구현
- 세션 기능 수정
<br>
- @kcs-developers/start-dream-team @soojik @Jooney-95 
close #이슈번호

feat: notify && fix: session service

---

src/App.tsx
src/components/live/CalendarPopUp.tsx
src/components/live/CreateRoomModal.tsx
src/components/live/CreateScheduleModal.tsx
src/components/live/LiveList.tsx
src/components/live/MentorProfile.tsx
src/components/live/RoomList.tsx
src/components/live/ShowMentoring.tsx
src/components/live/ShowSchedule.tsx
src/pages/Mentoring.tsx
src/recoil/scheduleSubscriptionState.ts

- fix: modify notify logic
<br>
- fix: modify notify logic 수정하였습니다
- 구독, 구독 취소, 스케쥴링 처리 등 수정하였습니다
<br>
close #이슈번호

fix: modify notify logic

---

src/App.tsx

- fix: location remove
<br>
- fix: location remove 변수 확인 못해서 삭제
<br>
close #이슈번호

fix: location remove

---

src/App.tsx
src/recoil/scheduleSubscriptionState.ts
src/recoil/subscriptionState.ts

- fix: recoil reset && notify error logic
<br>
- fix: recoil reset && notify error logic, 추후 작업을 위해 recoil 초기화 추가
- notify 에러 시 일부 처리 지연 추가
<br>
- ***
close #이슈번호

fix: recoil reset && notify error logic

---

src/App.tsx
src/recoil/scheduleSubscriptionState.ts
src/recoil/subscriptionState.ts

- fix: reset change
<br>
- fix: reset change하여 리코일 초기화
<br>
- ***
close #이슈번호

fix: reset change

---

src/App.tsx
src/components/live/CalendarPopUp.tsx
src/components/live/MentorProfile.tsx
src/components/live/ShowSchedule.tsx

- fix: notify condition modify
<br>
- fix: notify condition modify 수정..
<br>
- ***
close #이슈번호

fix: notify condition modify

---

src/App.tsx

- fix: notify err
<br>
- fix: notify err로 주석처리
<br>
close #이슈번호

fix: notify err

---

src/components/live/CalendarPopUp.tsx
src/components/live/CreateRoomModal.tsx
src/components/live/CreateScheduleModal.tsx
src/components/live/LiveList.tsx
src/components/live/MentorProfile.tsx
src/components/live/MentorScheduling.tsx
src/components/live/ModifyRoomInfo.tsx
src/components/live/ModifySchedule.tsx
src/components/live/ShowMentoring.tsx
src/components/live/ShowSchedule.tsx
src/pages/Mentoring.tsx

- fix: axios url err
<br>
- fix: axios url err 오류로 인해 process.env. 하위 내용 전체 삭제
<br>
close #이슈번호

fix: axios url err

---

src/components/live/ShowSchedule.tsx

- fix: session enter&&delete modify
<br>
- 클라이언트에서 nbf, exp(dailyco room 속성)을 unix timestamp로 변환해서 받아옵니다
- 시작하기 10분 전부터 모든 입장, 취소, 삭제 로직을 구현하게 변경하였습니다
<br>
close #이슈번호

fix: session enter&&delete modify

---

src/components/live/CalendarPopUp.tsx
src/components/live/CreateRoomModal.tsx
src/components/live/MentorProfile.tsx
src/components/live/ShowSchedule.tsx

- hotfix: mentoring save modify
<br>
- 현재 방 신청이 안되어(알림과 겹침) 관련 axios 처리 수정하였습니다
<br>
- @kcs-developers/start-dream-team @soojik @Jooney-95 
close #이슈번호

hotfix: mentoring save modify

---

src/components/problem/ClientDetailob.tsx
src/components/problem/ClientDetailsb.tsx
src/components/problem/ProblemPointModal.tsx

- 문제정답시 포인트증가 이벤트 위치변경
<br>
- 기존: 모달창 ok눌렀을시 axios요청 보냄 -> 변경: 문제 제출일시 정답이면 axios요청 보냄
- 기존: 문제 답안 작성없이 제출해도 제출이 됐음 -> 문제 답안 작성없이 문제 제출 불가
<br>
- @Jooney-95 @EagerProgrammer @kcs-developers/start-dream-team 
close #이슈번호

[Fix] 문제정답시 포인트증가 이벤트 위치변경

---

package-lock.json
src/components/Tags.tsx
src/components/mypage/NicknameInput.tsx
src/pages/MyPage.tsx
yarn.lock

-
<br>
1. MyPage
- 멘토등록
- 닉네임 공백제거
- 회원탈퇴
2. Tag컴포넌트 - 리스트없으면 출력안하게 수정
<br>
- ***
close #이슈번호

feat: MyPage - 멘토등록, 닉네임 공백제거, 회원탈퇴, Tag 수정

---

src/components/problem/ClientDetailob.tsx
src/components/problemRegister/HashTagBox.tsx
src/components/problemRegister/ProblemRegisterBox.tsx

- HashTag 수정사항 및 Css 수정
<br>
- HashTag 수정사항 및 Css 수정
<br>
- @soojik @Jooney-95 @paduck-96 @ITfervor 
close #이슈번호

[Fix] HashTag 및 여러 수정사항

---

src/components/problemRegister/ProblemRegisterBox.tsx

- HashTag 수정
<br>
- HashTag 수정
<br>
- ***
close #이슈번호

[Fix] : HashTag 수정

---

src/components/problemRegister/ProblemRegisterBox.tsx

- HashTag 오류 재수정
<br>
- HashTag 오류 재수정
<br>
- ***
close #이슈번호

Fix : HashTag 다시 수정하기

---

src/components/problem/ClientDetailob.tsx
src/components/problem/ClientDetailsb.tsx
src/components/problem/ProblemPointModal.tsx

- 페이지 새로고침 수정
<br>
- 페이지 리다이렉트 없이 값이 변경되도록 수정
<br>
- @EagerProgrammer 
close #이슈번호

fix: 페이지 새로고침 수정

---

src/components/live/ShowSchedule.tsx

- 취소 버튼 수정
<br>
- 취소 버튼 디스플레이 로직 수정
<br>
close #이슈번호

fix: 취소 버튼 수정

---

src/components/problemRegister/ProblemRegisterBox.tsx

- Pathname 수정
<br>
- Pathname 수정
<br>
- ***
close #이슈번호

Fix : pathnmae 수정

---

src/components/problem/ClientDetailob.tsx
src/components/problem/ClientDetailsb.tsx

- 새로고침 수정
<br>
- 새로고침 수정
<br>
- @EagerProgrammer 
close #이슈번호

[Fix] 새로고침 수정

---

src/components/problem/ClientDetailob.tsx
src/components/problem/ClientDetailsb.tsx
src/components/problem/ProblemPointModal.tsx

- 상세페이지 수정
<br>
- 상세페이지 새로고침 수정
<br>
- ***
close #이슈번호

[Fix] 상세페이지 수정

---

src/components/problemRegister/ProblemRegisterBox.tsx

- 첨부파일 수정 삭제 기능
<br>
- 첨부파일 수정 삭제 기능
<br>
- ***
close #이슈번호

[Fix] : 첨부파일 수정 삭제 기능

---

src/components/problem/ClientDetailob.tsx
src/components/problem/ClientDetailsb.tsx
src/components/problem/ProblemPointModal.tsx

- 상세페이지 수정
<br>
- 상세페이지 새로고침에서 리렌더링으로 수정하였습니다
<br>
- @EagerProgrammer 
close #이슈번호

[Fix] 상세페이지 리렌더링

---

src/components/live/CreateScheduleModal.tsx
src/components/live/LiveList.tsx
src/components/live/MentorScheduling.tsx
src/components/live/ModifySchedule.tsx
src/components/problemRegister/ProblemRegisterBox.tsx

- 모달창 닫기 수정 및 문제 등록 수정
<br>
- 모달창 따로 제출하지 않고 단순히 닫을 때는 reload 없도록 수정했습니다.
- 해시태그 관련하여 문제 등록 로직 수정되었습니다.
<br>
close #이슈번호

fix: 모달창 닫기 수정 및 문제 등록 수정

---

src/components/problemRegister/ProblemRegisterBox.tsx

- 문제 등록시 첨부파일 미리보기 및 객관식 답안 제한
<br>
- 문제 등록시 첨부파일 미리보기 및 객관식 답안 제한
<br>
- ***
close #이슈번호

[Fix] 문제 등록 첨부파일 수정

---

src/App.tsx
src/components/live/CalendarPopUp.tsx
src/components/live/CreateRoomModal.tsx
src/components/live/MentorProfile.tsx
src/components/live/ShowSchedule.tsx

- feat: notify logic
<br>
- feat: notify logic 을 위해 알림 처리 작성하였습니다
<br>
close #이슈번호

feat: notify logic

---

src/components/problemRegister/ProblemRegisterBox.tsx

- 첨부파일 마지막 수정
<br>
- 첨부파일 마지막 수정
<br>
- ***
close #이슈번호

[Fix] : 첨부파일 마지막 수정

---

src/components/problemRegister/ProblemRegisterBox.tsx

- Fix : 마무리 수정
<br>
- Fix : 마무리 수정
<br>
- ***
close #이슈번호

Fix : 마무리 수정

---

src/components/live/MentorScheduling.tsx
src/components/live/ModifySchedule.tsx

- 팝업 창 닫기
<br>
- 새로고침이 필요없는 경우는 단순히 팝업창 닫기만 되도록 수정했습니다.
<br>
- @kcs-developers/start-dream-team @paduck-96 @paduck-96 
close #이슈번호

fix: 팝업 창 닫기

---

src/apis/apis.ts
src/components/Modal.tsx
src/components/mypage/BadgeList.tsx
src/pages/MyPage.tsx

-
<br>
1. 마이페이지
- 칭호 조회, bignner 획득 등록 완료
2. Popup => Modal 변경 - 임시 2개 구현
- popup width 값이 고정되어있었음 => 마이페이지에선 너무 큰 width값 => 이 값을 없애고 Popup 컴포넌트가 사용되는 곳에서 width 적용하게 하는 방식으로 하려 했는데
- 멘토링에선 Popup 사용위치가 많아서 다 수정하기가 힘들것으로 보임
- 그래서 임시로 popup에서 width 값만 뺀 modal 하나 만들어서 마이페이지에 붙임
<br>
- ***
close #이슈번호

feat: 칭호 조회,획득 / Modal 추가

---

src/components/mypage/BadgeList.tsx
src/pages/MyPage.tsx

-
<br>
- 마이페이지 첫 화면에서도 칭호 착용 조회
<br>
- ***
close #이슈번호

chore: 착용칭호 조회

---

src/components/problemRegister/ProblemRegisterBox.tsx

- RegisterBox내부 해시태그 개수 제한 완료
<br>
- RegisterBox내부 해시태그 개수 제한 완료
<br>
- @EagerProgrammer 
close #이슈번호

Fix: 해시태그 갯수 제한

---

src/components/live/MentorProfile.tsx

- 알람 버튼 수정
<br>
- 알람 on/off 버튼, 내가 멘토인 방에 대해서는 안보이도록 수정했습니다.
- 버튼명을 `구독` -> `알람`으로 변경했습니다.
<br>
close #이슈번호

fix: alarm service

---

src/App.tsx

- fix: notify time modify
<br>
- fix: notify time modify를 위하 시간 간격을 조정하였습니다
- 1분 간격을 주어 무조건 발송하는 것보다 1/2 줄였습니다
<br>
close #이슈번호

fix: notify time modify

---

src/App.tsx
src/pages/MyPage.tsx

- hotFix: 무한 useEffect && recoil reset
<br>
- hotFix: 무한 useEffect 발견하여 디펜던시 수정
- 로그아웃 시 recoil reset 추가
<br>
close #이슈번호

hotFix: 무한 useEffect && recoil reset

---

src/App.tsx
src/components/live/CalendarPopUp.tsx

- fix: notify useEffect
<br>
- notify useEffect 오류로 수정 중입니다
<br>
close #이슈번호

fix: notify useEffect

---

src/components/live/CreateRoomModal.tsx
src/components/live/CreateScheduleModal.tsx
src/components/live/LiveList.tsx
src/components/live/MentorProfile.tsx
src/components/live/MentorScheduling.tsx
src/components/live/ModifyRoomInfo.tsx
src/components/live/ModifySchedule.tsx
src/components/live/SearchBar.tsx
src/components/live/ShowSchedule.tsx

- 검색로직 수정
- 방생성 모달창 수정
<br>
- 검색어 입력은 3글자 이상만 되도록 수정했습니다.
- 방 생성 모달창에서 input field 가 명확히 보이도록 수정했습니다.
<br>
close #이슈번호

fix: searchbar, room creating modal

---

src/pages/MyPage.tsx

- 중복 닉네임 변경에 대한 알림 수정
<br>
- 마이페이지에서 이미 사용중이 닉네임으로 변경될 경우 변경은 되지 않고 성공했다는 알림창을 변경이 불가하다는 알림으로 수정했습니다.
<br>

[FIx] 중복 닉네임 변경에 대한 알림 수정

---

src/components/problem/ClientDetailob.tsx
src/components/problem/ClientDetailsb.tsx

-
<br>
1. 문제 상세페이지 
- 객관식
- 풀기 전
- 푼 후
- 주관식
<br>
- ***
close #이슈번호

style: ob, sb detail

---

package-lock.json
package.json
src/components/SearchBox.tsx
src/pages/Problem.tsx
yarn.lock

- 문제 목록 검색 초기화 버튼 디자인 수정
<br>
- 문제 목록  페이지에서 검색 초기화 버튼 디자인을 수정했습니다.
<br>

[Fix] 문제 목록 검색 초기화 버튼 디자인 수정

---

src/components/live/CalendarPopUp.tsx
src/components/live/LiveList.tsx
src/components/live/MentorProfile.tsx
src/components/live/SearchBar.tsx
src/components/live/ShowMentoring.tsx

- 모달창에서 버튼 위치 수정
- 알람 버튼 display 로직 수정
<br>
- 모달창에서의 버튼 오른쪽으로 위치하도록 수정했습니다.
- 비회원은 알람버튼 활성화 안되도록 수정되었습니다.
<br>
close #이슈번호

fix: modal button, alarm button

---

src/App.tsx
src/components/live/MentorProfile.tsx
src/components/live/ShowSchedule.tsx

- fix: notify logic fix
<br>
- 새로고침을 강제적으로 적용하여 반영 여부 빠르게 수정
- useEffect 사항 수정
<br>
- @kcs-developers/start-dream-team @soojik @Jooney-95 
close #이슈번호

fix: notify logic fix

---

src/App.tsx

- hotFix: 무한 새로고침
<br>
- fix: 무한 새로고침, useEffect 수정
<br>
- @kcs-developers/start-dream-team @Jooney-95 
close #이슈번호

fix: 무한 새로고침

---

src/App.tsx
src/components/live/CalendarPopUp.tsx
src/components/live/MentorProfile.tsx
src/components/live/ShowSchedule.tsx

- fix: notify useEffect modify
<br>
- fix: notify useEffect modify, 멘토링 프로파일 컴포넌트에 useEffect 적용
- App.tsx에 useRef 적용
<br>
- @kcs-developers/start-dream-team @Jooney-95 
close #이슈번호

fix: notify useEffect modify

---

src/components/live/MentorProfile.tsx

- fix: mentorprofile useEffect modify
<br>
- fix: mentorprofile useEffect modify, 알림 문구 정상 작동을 위해 useEffect 수정
<br>
- @kcs-developers/start-dream-team @Jooney-95 
close #이슈번호

fix: mentorprofile useEffect modify

---

src/components/live/CalendarPopUp.tsx

- fix: 오타 수정
<br>
- fix: 오타 수정, live 오타 수정
<br>
close #이슈번호

fix: 오타 수정

---

src/App.tsx
src/components/MainList.tsx
src/components/mypage/AddressInput.tsx
src/components/mypage/CareerInput.tsx
src/components/mypage/NicknameInput.tsx
src/components/mypage/PwdInput.tsx
src/components/mypage/ResumeEdit.tsx
src/pages/Main.tsx
src/pages/MyPage.tsx

-
<br>
1. 마이페이지
- 남이 보는 마이페이지 
- 링크 예시 - `/profile/${el.memberId}` 변경불가하고 고유한 memberId로 마이페이지 링크가 구성되어져있음
```
<Link
to={`/profile/${el.memberId}`}
>
{el.nickname}
</Link>
```
2. 메인
- css 수정
3. App.js 수정은
nickname없을 때 에러나서 `?. `있을때 탐색하게끔 수정함
- memberInfo.nickname 에서
memberInfo?.nickname로 수정함
<br>
- ***
close #이슈번호

chore: MyPage 분기, Main css

---

src/components/live/CalendarPopUp.tsx

- fix: schedule register && reload
<br>
- fix: schedule register && 자동 reload 여부 확인
<br>
close #이슈번호

fix: schedule register && reload

---

src/components/live/CalendarPopUp.tsx
src/components/live/MentorProfile.tsx

- fix: mentorprofile 알림 처리
<br>
- fix: mentorprofile 알림 처리, 금일 물어봤던 사항 테스트
<br>
- ***
close #이슈번호

fix: mentorprofile 알림 처리

---

src/components/live/CalendarPopUp.tsx
src/components/live/MentorProfile.tsx

- fix: alarm useEffect modify
<br>
- fix: alarm useEffect modify를 위해 일부 로직 수정
<br>
close #이슈번호

fix: alarm useEffect modify
